import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Banner from '@/components/Banner'
import {sanityClient,urlFor} from "sanity.js"
import { Post } from 'typings'


interface Props{
  posts:[Post]
}
export default function Home({posts}:Props) {
  return (
    <>
      <Head>
        <title>Medium2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='max-w-7xl mx-auto'>
        <Navbar />
        <Banner />
        <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap:3 md:gap-6 p-2 md:p-6'>
          {posts.map(function(post){
            return(
              <div className='border'>
              <img className='h-60 w-full object-cover' src={urlFor(post.mainImage).url()!}/> 
              <div className='flex justify-between items-center p-3'> 
                <div>
                <h1 className='font-bold text-lg'>{post.title}</h1>
                <p>By: {post.author.name}</p>
                </div>
                <img className='w-12 h-12 rounded-full' src={urlFor(post.author.image).url()!}/>
              </div>
              </div>
            );
          })}
        </div>
      </div>
    </>
  )
}
export const getServerSideProps = async () =>{
  const query = `
  *[_type=="post"]{
    _id,
    title,
    slug,
    author ->{
      name,
      image
    },
      mainImage,
      slug
  }
  `
  const posts = await sanityClient.fetch(query)
  return{
    props:{
      posts,
    }
  }
}
